/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class islam_test_NativeGameWrapper */

#ifndef _Included_islam_test_NativeGameWrapper
#define _Included_islam_test_NativeGameWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     islam_test_NativeGameWrapper
 * Method:    SetSurface
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_islam_test_NativeGameWrapper_SetSurface
  (JNIEnv *, jclass, jobject);

/*
 * Class:     islam_test_NativeGameWrapper
 * Method:    Start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_islam_test_NativeGameWrapper_Start
  (JNIEnv *, jclass);

/*
 * Class:     islam_test_NativeGameWrapper
 * Method:    Stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_islam_test_NativeGameWrapper_Stop
  (JNIEnv *, jclass);

/*
 * Class:     islam_test_NativeGameWrapper
 * Method:    Press
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_islam_test_NativeGameWrapper_Press
  (JNIEnv *, jclass);

/*
 * Class:     islam_test_NativeGameWrapper
 * Method:    Play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_islam_test_NativeGameWrapper_Play
  (JNIEnv *, jclass);

/*
 * Class:     islam_test_NativeGameWrapper
 * Method:    Pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_islam_test_NativeGameWrapper_Pause
  (JNIEnv *, jclass);

/*
 * Class:     islam_test_NativeGameWrapper
 * Method:    Release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_islam_test_NativeGameWrapper_Release
  (JNIEnv *, jclass);

/*
 * Class:     islam_test_NativeGameWrapper
 * Method:    IsOver
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_islam_test_NativeGameWrapper_IsOver
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
